### ISSUE TITLE
Cannot find name Extract

### ISSUE THREAD

**Issue by Thaval** [UselessPickles/ts-enum-util#5]
I'm using ts-enum-util: "^3.1.0. The error occurs in index.d.ts and is as follows:

> Error: ERROR in node_modules/ts-enum-util/dist/types/index.d.ts(15,23): error TS2304: Cannot find name 'Extract'.

Until now, I'm gonna stick to Object.Keys..

**Comment by UselessPickles** [comment]
Sounds like you are using TypeScript version 2.7 or earlier, which does not have `Extract`. As described by the "Requirements" section of the README, version 3 of ts-enum-util requires TypeScript 2.8+. 

Use the latest of major version 2 of ts-enum-util for older versions of TypeScript.

There was a breaking change to how `keyof` works in TypeScript as of 2.9, and I had to make use of `Extract` to get correct types in 2.9+, but `Extract` was new as of TS 2.8. There's no solution that is compatible with all versions of TypeScript, so i have to maintain 2 separate major versions of this package for 2 different version ranges of TypeScript.

**Comment by UselessPickles** [comment]
Link to "Requirements" section of README for v3.1.0 for reference: https://github.com/UselessPickles/ts-enum-util/tree/v3.1.0#requirements

**Comment by UselessPickles** [comment]
I'll try to clarify this better in the README. Maybe reorganize the sections and/or mention it in a section that is more likely to be viewed.

**Comment by UselessPickles** [comment]
README has been improved as of version 4.0.0
